pmorissette/ffn

ffn/core.py

`PerformanceStats.return_table` now has months as column names instead of former 1..13 (13 for YTD).
Thus printing `PerformanceStats.return_table` is consistent with `PerformanceStats.display_monthly_returns()`.

PerformanceStats.return_table now has months as column names

---

ffn/core.py

Two fixes for calculation of `return_table`:
1. Assignment of column names raises an exception in case of empty `return_table` (introduced by #2)
2. Calculation of `return_table` raises `ZeroDivisionError` in case when first return (p[0]) is 0

Small fixes: return_table

---

ffn/core.py

Minor addition to #4: setter of the risk-free rate for the `GroupStats` and output in the `display()`

Minor changes: risk-free rate setter and output for GroupStats

---

ffn/core.py

Philippe, hi again.
Here I removed awfully slow loops and replaced `to_drawdown_series` with vectorized version. Improves speed by a factor of 100-1000.
E.g. for 
```
data = bt.get('^GSPC', start='1973-01-01')
%timeit df0 = data.to_drawdown_series()
```
Elapsed time dropped from 8.68s to 2ms for my laptop.

Improved speed of to_drawdown_series

---

ffn/core.py

If some returns series supplied to `calc_inv_vol_weights()` are equal to zero, then inverse-volatility will be infinite.
I suggest to remove assets with zero volatility from the portfolio rather than returning a list of zeros (sum of all weights will be also infinite -> individual weights of good assets are equal to zero).
There're three options:
- we can drop these assets (`dropna()` [here](https://github.com/vfilimonov/ffn/commit/91e89982579c06f83a61ae1dac134cfdeb5e1e83#diff-a34fa4843ef91ea804e63075ff7565d4R1278))
- we can set their weights to zero  (`fillna(0)` [here](https://github.com/vfilimonov/ffn/commit/91e89982579c06f83a61ae1dac134cfdeb5e1e83#diff-a34fa4843ef91ea804e63075ff7565d4R1278))
- we can return `NaN` for them
I think the last variant is better: user might expect series of …

Fix for calc_inv_vol_weights() in case of zero volatility

---

ffn/core.py

notice that .iteritems() has been abolished in python 3.x,using .items() instead when AttributeError occurs

fixed an AttributeError in ffn.calc_clusters

---

ffn/core.py

Hello and thank you for your great library!
The humble changes in this PR implement the ulcer performance index (you may want to double check my computations, but from my testing the results look valid). The other change, which I didn't mean to include but Github's interface is confusing, replaces a .iteritems() call (which apparently isn't available in python3) with .items().
Thanks

Ulcer performance index, python3 compat fix

---

ffn/core.py
tests/test_core.py

Addition of calc_erc_weights() to calculate the portfolio weights which equate to having an equal risk contribution. The function is called in similar way to the existing calc_mean_var_weights() and calc_inv_vol_weights() and the test script has also been added.
The resulting portfolio is similar to a minimum variance portfolio subject to a diversification constraint on the weights of its components and its volatility is located between those of the minimum variance and equally-weighted portfolios (Maillard 2008).
The code draws heavily on examples and code provided in Roncalli (2013) and the solution uses a cyclical coordinate descent (CDD) algorithm described in detail in Griveau-Billion, 2013.
```python  
def calc_erc_weights(returns,
initial_weights=None,
risk_weights=None, …
```

ERC / Risk Parity Portfolio Weights

---

ffn/core.py
tests/test_core.py

`any(>limit)` is faster than `not np.all(<=limit)` -- 2x in smaller data, 5-10x in larger data. Although, not significant in larger scheme of things. Accept this change as you seem fit :-) And, test case has  been updated, to do same tests in lesser LOC.
```python
In [138]: res = pd.Series(np.random.rand(100))
In [139]: %timeit not np.all([x <= 0.3 for x in res])
10000 loops, best of 3: 55.4 µs per loop
In [140]: %timeit any(x > 0.3 for x in res)
10000 loops, best of 3: 29.4 µs per loop
In [141]: res = pd.Series(np.random.rand(10000))
In [142]: %timeit not np.all([x <= 0.3 for x in res])
1000 loops, best of 3: 1.5 ms per loop
In [143]: %timeit any(x > 0.3 for x in res)
10000 loops, best of 3: 198 µs per loop
```

REF: Use builtin any over not np.all

---

ffn/core.py

This lets users say `ax = ...plot()` and then add another line to the
same plot by adding a keyword argument `ax=ax` to the next plot call.

Return axes object from all plot methods

---

ffn/core.py

In the latest version of Pandas, Series objects don't have the order method anymore. The method sort_values was introduced in Pandas 0.17.0
Fixes #46

Update calc_ftca method to use Series.sort_values

---

tests/test_core.py

This PR fixes
In `test/test_core.py`
- use `.loc` instead of `.ix` -- `.ix` is deprecated.
- Add spaces for pep8 compliance

REF: test_core.py for spaces, .loc

---

ffn/core.py

Hello Jordan,
I had done a small mistake with the data checking, which made the calculus of "three_month" and "six_month" not running when the data is of a lower frequency than monthly (e.g. quarterly like in the following example). While logically the condition that has to be met is only that the minimum frequency is three month and six month respectively in those cases. And I extended these conditions to three_year, five_year and ten_year.
Output of lookback_returns before correction:
(Don't pay attention to 1w, wtd, and qtd figures. They are added in my local version but I didn't push them to github)
Here is the proposed correction.
Best regards,
Viktor

Data frequency check extended + correction

---

ffn/core.py

This PR updates the documentation of the supported methods for risk parity computation.

update documentation of argument risk_parity_method

---

ffn/core.py
tests/test_core.py

**Fixed bug in YTD and MTD calculation.** 
YTD and MTD are not calculated for short return series, and are not necessarily equal to total_return. 
MTD is only assigned something other than total_return, if more than one monthly return exists - which is unnecessary. 
Same issue for YTD - but with a stricter condition of more data before it is calculated. 
MTD and YTD returns are calculated after validating that a single daily return is available. If in the same month, the dp series can be used to find MTD, else the second to last value in the mp series is used. Same method for YTD calculation.

Update ytd and mtd calculation

---

.gitignore
ffn/core.py

The `pandas` upgrade from 2.0.3 to 2.1.0 is causing warnings to be generated related to the following deprecations:
1) Deprecated the method and limit keywords on [Series.fillna()](https://pandas.pydata.org/docs/reference/api/pandas.Series.fillna.html#pandas.Series.fillna), [DataFrame.fillna()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html#pandas.DataFrame.fillna), [SeriesGroupBy.fillna()](https://pandas.pydata.org/docs/reference/api/pandas.core.groupby.SeriesGroupBy.fillna.html#pandas.core.groupby.SeriesGroupBy.fillna), [DataFrameGroupBy.fillna()](https://pandas.pydata.org/docs/reference/api/pandas.core.groupby.DataFrameGroupBy.fillna.html#pandas.core.groupby.DataFrameGroupBy.fillna), and [Resampler.fillna()](https://pandas.pydata.org/docs/reference/api/pandas. …

Fix pandas deprecation warnings

---

ffn/core.py

This pull request introduces enhancements to the calc_perf_stats function within the ffn/core.py module. Specifically, it modifies the function signature to accept two additional arguments: risk_free_rate, with a default value of 0.0, and annualization_factor, with a default value of 252, representing the number of trading days in a year. These changes allow for more detailed performance statistics calculations by incorporating the annual risk-free rate and adjusting the calculations based on the specified annualization factor. The pull request includes 4 additions and 2 deletions, aiming to improve the flexibility and accuracy of performance statistics calculations for financial analysis.

Add risk free rate

---

ffn/data.py
ffn/utils.py

I personally use type checking with python with the help of type hinting for autocompletions. It is very common for high used modules to integrate type hinting for good integration and workflow with other modules and files.
Its absence is fairly noticeable by me. Example from my code is shown below. Assuming that the `utils.get` method returns a dataframe rather than an unknown object, might greatly increase the user's experience via autocompletion.

Add typing for the `utils` file

---

ffn/data.py
pyproject.toml

As noted in https://github.com/pydata/pandas-datareader/issues/977 ,  `pandas_datareader` is unmaintained for 3+ years, and many of the readers are broken. Additionally, even importing `pandas_datareader` is broken in Python 3.12 . Therefore it is time for `ffn` to remove support for using said library. 
Related issue: 
https://github.com/pmorissette/ffn/issues/237

Removing unmaintained pandas_datareader

---

tests/test_utils.py

I saw that the `as_format` function from `utils.py` has an obsolete `applymap` method from pandas.
The as_format function from utils.py is not covered by the test, that's why there is no warning in Actions because of this.. After this PR, I will make another one where I will make the processing of the outdated applymap, like [here.](https://github.com/pmorissette/ffn/pull/235)

The as_format function from utils.py is not covered by the test.
